@startuml analog
class AnalogOut {
    - pin: Pin
    - resolution: usize
    - frequency: usize

    + new(): AnalogOut
    + set_value(value: usize)
    + set_frequency()
    + set_resolution()
}

class AnalogIn {
    - pin: Pin
    - resolution: usize
    - frequency: usize

    + new(): AnalogIn
    + trigger_when(condition: AnalogicTriggerCondition, func)
    + trigger_first_n_times(condition: AnalogicTriggerCondition, amount_of_times: usize, func)
    + read(): usize
    + set_frequency()
    + set_resolution()
}

enum AnalogicTriggerCondition {
    HigherThan(u32)
    InRange(u32, u32)
    OutOfRange(u32, u32)
    LowerThan(u32)
}

AnalogIn --> AnalogicTriggerCondition
@enduml