@startuml Wifi Driver

class Wifi_driver{
    -controller: AsyncWifi<EspWifi>
    +connect()
    +is_started()
    +is_connected()
    +get_address_info()
    +get_dns_info()
    +get_http_client()
    +get_https_client()
}

interface Http{
    +post(string, vec<(&'a str,&'a str)>)
    +get(string, vec<(&'a str,&'a str)>)
    +put(string, vec<(&'a str,&'a str)>)
    +delete(string, vec<(&'a str,&'a str)>)
    +patch(string, vec<(&'a str,&'a str)>)
    +head(string, vec<(&'a str,&'a str)>)
    +options(string, vec<(&'a str,&'a str)>)
    +response_status(string, vec<(&'a str,&'a str)>)
    +response_status_message()
    +wait_for_response([u8])
}

class HttpClient{
    -connection: EspHttpConnection
    +get_connection()
    
}

class HttpsClient{
    -connection: EspHttpConnection
    +get_connection()
}

class HttpHeader {
    header_type: HttpHeaderType,
    value: string
    +to_string()
}


Wifi_driver ..> HttpClient: create
Wifi_driver ..> HttpsClient: create
HttpClient --> Http
HttpsClient --> Http
Http -> HttpHeader


@enduml